### ISSUE TITLE
Update guzzle requiriment to ^6.3.0

### ISSUE THREAD

**Issue by andrelopez** [viniciusgava/google-translate-php-client#11]
Hi,

Could you please update guzzle requirement to ^6.3.0

`"guzzlehttp/guzzle": "^6.3.0"`

Thank you

**Comment by andrelopez** [comment]
Blocked by https://github.com/enupal/translate/issues/30

**Comment by viniciusgava** [comment]
Hey Andre, could you send a pull request with the changes?

**Comment by andrelopez** [comment]
@viniciusgava I just submitted the PR. Looking forward to hearing from you. Thank you!

**Comment by andrelopez** [comment]
Hi @viniciusgava Hope all is well. Any update on this?

**Comment by viniciusgava** [comment]
@andrelopez PR Merged.
New release: https://github.com/viniciusgava/google-translate-php-client/releases/tag/2.1.0

**Comment by andrelopez** [comment]
@viniciusgava Thank you! 💯
