### ISSUE TITLE
Update to guzzle ^7.0.1

### ISSUE THREAD

**Issue by michaloravec** [viniciusgava/google-translate-php-client#14]
Could you upgrade to guzzlehttp/guzzle version ^7.0.1? Because this package can't be use on Laravel 8.

**Comment by viniciusgava** [comment]
Yes @michaloravec , we can update the **v3** to **guzzlehttp/guzzle ^7.0.1**. 
Could you send a Pull Request?

**Comment by michaloravec** [comment]
I found out that guzzle v7.0. is not neccessary for Laravel 7. So it's still ok.

**Comment by maxpdesign** [comment]
Can this be reopened and upgraded to ^7.0.1? I'm getting dependency conflicts in Craft CMS because other plugins are starting to use guzzle 7 instead of 6

**Comment by viniciusgava** [comment]
@maxpdesign I think we can. Any reason to not update direct for guzzle 7.3? it is been release 6 months ago. 
https://github.com/guzzle/guzzle/releases/tag/7.3.0

**Comment by viniciusgava** [comment]
@maxpdesign @michaloravec I open a PR updating guzzle 7. Could you check if works for your? 
Once you confirm it is working, I'll publish as 3.1.0.

Refer to test this branch: `dev-guzzle-7`.
Pull Request: https://github.com/viniciusgava/google-translate-php-client/pull/15

**Comment by jacotijssen** [comment]
I tested this and it works, is there a possibility to merge the PR?

**Comment by viniciusgava** [comment]
@maxpdesign @michaloravec @jacotijssen published as `3.1.0`. Dev branch has been removed.
